version: "3.9"

services:
  db:
    container_name: "db_postgres"
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=zdjecia
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d

volumes:
  db_data:
